# -*- coding: utf-8 -*-
"""Modul Penjumlahan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15IsjEqEyT80EMH4VdL9tMN-RiG1AICFb
"""

def penjumlahan (angka_1, angka_2):
  jumlah = angka_1 + angka_1
  return jumlah